# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: tf_folder
  value: $(System.DefaultWorkingDirectory)/13_storage_blob 


steps:
- script: |
      docker run --tty --volume $(tf_folder):/tf bridgecrew/checkov --directory /tf --compact
  displayName: Run Static Code analysis for Terraform using Checkov
